name: 'Lock inactive closed issues'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    name: "Lock"

    runs-on: ubuntu-latest

    steps:
      - name: "Lock"
        uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '31'
          issue-exclude-created-before: ''
          issue-exclude-labels: ''
          issue-lock-labels: ''
          issue-lock-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          issue-lock-reason: 'resolved'
          process-only: 'issues'
